name = "ChargedParticles"
uuid = "e91dad46-2c06-47f2-8668-7ffa57fde2d9"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
