name = "ChargedParticles"
uuid = "e91dad46-2c06-47f2-8668-7ffa57fde2d9"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Mendeleev = "c116f080-063d-490a-9873-2b5b2cce4c34"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.10"
Match = "2.2.0"
Mendeleev = "1.0.1"
Unitful = "1.21.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test"]
docs = ["Documenter"]

[workspace]
projects = ["test", "docs"]
